on:
  push:
    branches:
      - main
env:
  DEFAULT_ACCOUNT_ID: ${{ 147676365 }}
  DEFAULT_PERSONAL_ACCESS_KEY: ${{ CiRldTEtOTI3Zi0zYjk4LTRiZmEtYTc3ZC1jNjkwOTIzNTZiOTUQzbm1RhjZ1I4VKhkABeaRgilwIZSyLrIK8Po2njSoz6Gj4jAHSgNldTE }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Project Action
        uses: HubSpot/hubspot-project-actions@v1.1.0
